---

- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      update_cache: yes
  - name: Enable Docker service
    service:
      name: docker
      state: restarted
      enabled: yes
  - name: Create Docker group
    group:
      name: docker
      state: present
  - name: Add Docker to system group
    shell: "usermod -aG docker ubuntu"
  
