---

- hosts: all
  become: true
  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      update_cache: yes
  - name: Enable Docker service
    service:
      name: docker
      state: restarted
      enabled: yes
  - name: Create Docker group
    group:
      name: docker
      state: present
  - name: Add Docker to system group
    shell: "usermod -aG docker ${USER}"
  - name: Install K3S
    shell: "curl -sfL https://get.k3s.io | sh -"
  - name: Start and enable K3S
    service:
      name: k3s
      state: restarted
      enabled: yes
  - name: Copy K3S config to ~/.kube
    copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: ~/.kube/k3s_kubeconfig
      remote_src: yes
      mode: '0644'
  
